config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  post 'home/convert' => 'home#convert'

end

app/models/celsius_temperature.rb
class CelsiusTemperature < Temperature
  def to_farenheit
    temp = (value.to_f * (9.0/5.0)) + 32
    FarenheitTemperature.new(value: temp.round(2))
  end

  def value_text
    "#{value} &deg; C"
  end

  def converted_value_text
    send(convert_to).value_text
  end
end

app/models/farenheit_temperature.rb
class FarenheitTemperature < Temperature
  def to_celsius
    temp = (value.to_f - 32) * (5.0/9.0)
    CelsiusTemperature.new(value: temp.round(2))
  end

  def value_text
    "#{value} &deg; F"
  end

  def converted_value_text
    send(convert_to).value_text
  end
end

app/models/temperature.rb
class Temperature
  include ActiveModel::Model

  ALLOWED_CONVERSIONS = ['to_farenheit', 'to_celsius']

  attr_accessor :value, :type, :convert_to

  validates_presence_of :value, :type
  validates_presence_of :convert_to, allow_nil: true
  validates_inclusion_of :convert_to, in: ALLOWED_CONVERSIONS, allow_nil: true
end

app/models/temperature_adapter.rb
class TemperatureAdapter
  ALLOWED_TYPES = ['CelsiusTemperature', 'FarenheitTemperature']

  include ActiveModel::Model

  attr_accessor :temperature, :value, :type, :convert_to

  def initialize(attrs)
    raise ArgumentError, 'Invalid Temperature Type' unless ALLOWED_TYPES.include?(attrs[:type])
    @temperature = attrs[:type].constantize.new(type: attrs[:type], value: attrs[:value],
                                                convert_to: attrs[:convert_to])
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @temperature_adapter = TemperatureAdapter.new(value: 0, type: 'CelsiusTemperature')
  end

  def convert
    @temperature_adapter = TemperatureAdapter.new(permitted_params)
    @temperature = @temperature_adapter.temperature
    if @temperature.valid?
      @notice = "#{@temperature.value_text} is #{@temperature.converted_value_text}"
    else
      @error = "Please enter the proper values"
    end
    render :index
  end

  private

  def permitted_params
    params.require(:temperature_adapter).permit(:value, :type, :convert_to)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Temperature Converter

.home{ style: 'height: 400px; width: 1200px; position:absolute; top:30%; left:30%'}
  = form_for @temperature_adapter, url: home_convert_path do |f|
    = f.label :value, 'Celsius Temperture'
    = f.number_field :value
    = f.hidden_field :type, value: 'CelsiusTemperature'
    = f.hidden_field :convert_to, value: 'to_farenheit'
    = f.submit 'Get Farenheit Temp'

  %br/
  %br/
  - if @notice
    .success= @notice.html_safe
  - elsif @error
    .error= @error

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TempratureConverter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>